### ISSUE TITLE
你好，能否给个联系方式我呢？我有问题想要请教以下，十万火急。

### ISSUE THREAD

**Issue by whenTheMorningDark** [lanniu/mxgraph-cli-demo#1]
can you give me QQ or WeChat?,I need you help!!!! thanks.

**Comment by lanniu** [comment]
lanniu770314

**Comment by lanniu** [comment]
> can you give me QQ or WeChat?,I need you help!!!! thanks.

lanniu770314

**Comment by lanniu** [comment]
> can you give me QQ or WeChat?,I need you help!!!! thanks.

微信 lanniu770314
